# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Capstone' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Capstone

pod 'FBSDKCoreKit', '~> 4.10.0'
pod 'FBSDKLoginKit', '~> 4.10.0'
pod 'FBSDKShareKit', '~> 4.10.0'
pod ‘Firebase/Core’
pod ‘Firebase/Auth’


  target 'CapstoneTests' do

    inherit! :search_paths
    # Pods for testing
  end

  target 'CapstoneUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
